general:
  name: "structured_randimg_fd"
  recon: "spec"
  save: True

model:
  n_layers: 1
  diagonal_mode: "uniform_phase"
  transform: "fft"
  std: 1.0
  shared_weights: False
  drop_tail: True

image:
  img_size: 64
  mode: "random" # "random", "shepp-logan", "mix"
  noise_ratio: 0.8

recon:
  series: "arange"
  start: 2
  end: 194
  list: []
  n_repeats: 50
  max_iter: 5000

save:
  path: "../runs"
  name: "res_{model_name}_{oversampling_start}-{oversampling_end}_{recon}_{n_repeats}repeat.csv"