name: Bug report
description: Report a bug to help us improve DeepInverse.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below to help us reproduce and fix the issue.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, DeepInverse version, and any relevant dependencies.
      placeholder: e.g. Ubuntu 22.04, Python 3.12, DeepInverse 0.3.2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide a minimum reproducible example, including code and data if possible.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Full traceback (if applicable)
      description: Please paste the full error message and traceback here.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
