blank_issues_enabled: false
contact_links:
  - name: DeepInverse community support
    url: https://github.com/deepinv/deepinv/discussions
    about: Please ask and answer questions here.
  - name: DeepInverse maintainers
    url: https://github.com/deepinv/deepinv/blob/main/MAINTAINERS.md
    about: Please reach out to the maintainers for assistance.
