general:
  name: "structured_shepp_laplace_unit_mag_FDF"
  recon: "spec"
  save: True

signal:
  img_size: 64
  mode: "shepp-logan" # "random", "shepp-logan", "mix", "delta"， "constant"
  config:
    noise_ratio: 0.0 # noise ratio for mix mode
    unit_mag: True
    max_scale: 40.0 # max scale for varying mag

model:
  n_layers: 1.5
  diagonal:
    mode: 'laplace' # 'uniform_phase', 'gaussian', 'laplace', 'marchenko-pastur', 'student-t', 'uniform', 'triangular'
    config:
      degree_of_freedom: 30
      complex: True
      unit_mag: True
  transform: "fft"
  shared_weights: False

recon:
  series: "arange"
  start: 2
  end: 194
  list: []
  n_repeats: 50
  max_iter: 5000

save:
  path: "../runs"
  name: "res_{model_name}_{img_mode}_{recon}_{oversampling_start}-{oversampling_end}_{n_repeats}repeat.csv"