general:
  name: "structured_FDFD_laplace"
  recon: "spec"
  save: True

model:
  n_layers: 2
  diagonal_mode: "laplace"
  transform: "fft"
  shared_weights: False
  df: None
  drop_tail: True

image:
  img_size: 64
  mode: "shepp-logan" # "random", "shepp-logan", "mix"
  noise_ratio: 0.0

recon:
  series: "arange"
  start: 2
  end: 194
  list: []
  n_repeats: 50
  max_iter: 5000

save:
  path: "../runs"
  name: "res_{model_name}_{oversampling_start}-{oversampling_end}_{recon}_{n_repeats}repeat.csv"