general:
  name: "structured_FDF"
  recon: "spec"
  save: True

signal:
  img_size: 64
  mode: "random" # "random", "shepp-logan", "mix", "delta"
  config:
    varying_norm: False
    noise_ratio: 0.0 # noise ratio for mix mode
    max_scale: 3.0 # max scale for varying norm

model:
  n_layers: 1
  diagonal:
    mode: 'uniform_phase' # 'uniform_phase', 'gaussian', 'laplace', 'marchenko-pastur', 'student-t', 'uniform', 'triangular'
    config:
      degree_of_freedom: 30
      complex: True
  transform: "fft"
  shared_weights: False
  drop_tail: False

recon:
  series: "arange"
  start: 2
  end: 194
  list: []
  n_repeats: 50
  max_iter: 5000

save:
  path: "../runs"
  name: "res_{model_name}_{img_mode}_{recon}_{oversampling_start}-{oversampling_end}_{n_repeats}repeat.csv"