name: Comment Artifact URL for Fork PRs

on:
  workflow_run:
    workflows: ["Build docs"]
    types:
      - completed

permissions:
  pull-requests: write
  actions: read

jobs:
  comment-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Workflow Run Context
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
          echo "Workflow Event: ${{ github.event.workflow_run.event }}"
          echo "Workflow Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Repository: ${{ github.repository }}"
          echo "Head Repository: ${{ github.event.workflow_run.head_repository.full_name }}"
          echo "PR Numbers: ${{ toJSON(github.event.workflow_run.pull_requests) }}"
          echo "Head Branch: ${{ github.event.workflow_run.head_branch }}"
      - name: Get Artifact URL and Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the workflow run's artifacts from the base repository
          ARTIFACTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts")
          
          # Debug: Output raw artifacts response
          echo "Artifacts Response: $ARTIFACTS"
          
          # Extract the artifact URL for 'documentation'
          ARTIFACT_URL=$(echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.name == "documentation") | .archive_download_url' || echo "")
          
          # Get the PR number
          PR_NUMBER=$(echo '${{ toJSON(github.event.workflow_run.pull_requests) }}' | jq -r '.[0].number' || echo "")
          
          # Debug: Output extracted values
          echo "Artifact URL: $ARTIFACT_URL"
          echo "PR Number: $PR_NUMBER"
          
          # Generate nightly.link URL
          NIGHTLY_LINK="https://nightly.link/${{ github.repository }}/workflows/build-doc-preview/${{ github.event.workflow_run.head_branch }}/documentation.zip"
          echo "Nightly Link: $NIGHTLY_LINK"
          
          if [ -n "$ARTIFACT_URL" ] && [ -n "$PR_NUMBER" ]; then
            echo "Posting comment to PR #$PR_NUMBER"
            curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -X POST \
              -d "{\"body\": \"📄 The documentation for this PR has been built and is available for download: [Download documentation]($ARTIFACT_URL)\n\nFor public access, also available at: [nightly.link]($NIGHTLY_LINK)\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
          else
            echo "Error: Missing artifact URL or PR number. Cannot post comment."
            exit 1
          fi