name: Doctests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  doctest:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#doctests') }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      

    - name: Install deepinv and its dependencies
      run: |
        pip install -e .[denoisers,doc]
    - name: Install git repository optional dependencies
      run: |
        pip install git+https://github.com/fbcotter/pytorch_wavelets.git
        python3 -m pip install https://github.com/odlgroup/odl/archive/master.zip
    - name: Run doctests
      run: |
        for file in $(find . -name '*.py'); do
          echo "Running doctests in $file"
          python -m doctest -v $file
        done
