name: Expose docs

on: [status]

jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - uses: scientific-python/circleci-artifacts-redirector-action@v1   # pin to a release
        with:
          api-token:  ${{ secrets.CIRCLECI_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/dev/index.html
          circleci-jobs: build_docs
