name: Sync

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 02:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Setup Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/deepinv/deepinv.git
          git fetch upstream

      - name: Reset main branch to upstream/main
        run: |
          git checkout main
          git reset --hard upstream/main

      - name: Remove unwanted upstream workflows
        run: |
          rm -rf .github/workflows/*

      - name: Update sync.yml from sync branch
        run: |
          git fetch origin
          git checkout origin/sync -- .github/workflows/sync.yml

      - name: Commit changes if any
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "Sync upstream: remove unwanted workflows and restore sync workflow"

      - name: Push changes using PAT
        env:
          PAT_PUSH: ${{ secrets.PAT_PUSH }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_PUSH}@github.com/${{ github.repository }}.git
          git push origin main --force

      - name: Update sync branch
        run: |
          git checkout sync
          git reset --hard origin/main
          git push origin sync --force
