name: Test GPU

on:
  schedule:
    - cron: "30 2 */1 * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to test"
        required: true
        type: number

jobs:
  test:
    name: Test GPU
    runs-on: gpu
    env:
      DEEPINV_MOCK_TESTS: "True"
      DEEPINV_DOWNLOAD_VERBOSE: "False"
      WORKING_DIR: "/local/jtachell"

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha
                  || (inputs.pr_number && format('refs/pull/{0}/head', inputs.pr_number))
                  || github.sha }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: latest
          pixi-bin-path: /local/jtachell/pixi/bin/pixi

      - name: Check import
        run: |
          pixi run -e full python -c "import deepinv"

      - name: Restore .testmondata # Restore testmon data from main to speed up tests
        uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: .testmondata
          key: testmon-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            testmon-gpu-main-

      - name: Test with pytest
        run: |
          pixi run -e full pytest -n 2 --dist=loadgroup --testmon

      - name: Save .testmondata
        uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/main' # Only save cache on main branch
        with:
          path: .testmondata
          key: testmon-gpu-main-${{ github.run_id }}

      - name: Post result to PR
        if: always() && inputs.pr_number != ''
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.inputs.pr_number;
            const result = "${{ job.status }}";
            const runUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
      
            const body = result === "success"
              ? `✅ GPU tests passed\n\n🔗 [View run details](${runUrl})`
              : `❌ GPU tests failed\n\n🔗 [View run details](${runUrl})`;
      
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body,
            });

      - name: Cleanup Pixi
        if: always()
        run: |
          rm -rf /local/jtachell/pixi