name: Test main

on:
  schedule:
    # run test every day at 3:30 AM
    - cron: "30 3 */1 * *"
  push:
    branches:
    - main


# Cancel in-progress runs when pushing a new commit on the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ matrix.name }}
    if: ${{ github.repository == 'deepinv/deepinv' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Ubuntu tests
          - os: ubuntu-latest
            environment: full
            name: "ubuntu all optional dependencies"
          - os: ubuntu-latest
            environment: test
            name: "ubuntu no optional dependencies"
          # Windows tests
          - os: windows-latest
            environment: full
            name: "windows all optional dependencies"
    env:
      DEEPINV_MOCK_TESTS: "True"
      DEEPINV_DOWNLOAD_VERBOSE: "False"
    steps:
      - uses: actions/checkout@v5

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest

      - name: Restore .testmondata
        uses: actions/cache/restore@v3
        with:
          path: .testmondata
          key: testmon-cpu-main-${{ matrix.os }}-${{ matrix.environment }}-${{ github.run_id }}
          restore-keys: |
            testmon-cpu-main-${{ matrix.os }}-${{ matrix.environment }}
            testmon-cpu-main-${{ matrix.os }}

      # For debugging purposes
      - name: Check Python version
        run: pixi run -e ${{ matrix.environment }} python --version

      - name: Check installed packages
        run: pixi run -e ${{ matrix.environment }} pip list

      - name: Test with pytest and generate coverage report
        run: |
          pixi run -e ${{ matrix.environment }} pytest -n 2 --dist=loadgroup --cov=deepinv --junitxml=junit.xml -o junit_family=legacy --testmon

      - name: Save .testmondata
        uses: actions/cache/save@v3
        with:
          path: .testmondata
          key: testmon-cpu-main-${{ matrix.os }}-${{ matrix.environment }}-${{ github.run_id }}

      - name: Upload coverage to Codecov
        # Only upload coverage on Linux with full dependencies
        if: ${{ runner.os == 'Linux' && matrix.environment == 'full' }}
        uses: codecov/codecov-action@v5

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && runner.os == 'Linux' && matrix.environment == 'full' }}
        uses: codecov/test-results-action@v1
