name: Experimentation

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Experimentation
    runs-on: gpu

    steps:
      - name: Experimentation
        run: |
          hostname
