name: Test PRs

on:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            version_python: "3.9"
            environment: "test" # Matches [tool.pixi.environments]
            name: "ubuntu py3.9 no optional dependencies"
          - os: ubuntu-latest
            version_python: "3.12"
            environment: "full"
            name: "ubuntu py3.12 all optional dependencies"
          - os: windows-latest
            version_python: "3.12"
            environment: "full"
            name: "windows py3.12 all optional dependencies"
    env:
      DEEPINV_MOCK_TESTS: "True"
      DEEPINV_DOWNLOAD_VERBOSE: "False"

    steps:
      - uses: actions/checkout@v5

      # Pixi needs the pyproject.toml to be valid for the version we want BEFORE setup
      - name: Patch Python version for 3.9 compatibility
        if: matrix.version_python == '3.9'
        shell: bash
        run: |
          sed -i "s/>=3.10/>=3.9/" pyproject.toml

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          #cache: true
          #frozen: false

      - name: Python 3.9 check import warning
        if: matrix.version_python == '3.9'
        run: |
          pixi run -e ${{ matrix.environment }} python -c "import deepinv"

      - name: Restore .testmondata
        if: matrix.version_python == '3.12'
        uses: actions/cache/restore@v3
        with:
          path: .testmondata
          key: testmon-cpu-main-${{ matrix.os }}-${{ matrix.version_python }}-${{ github.run_id }}
          restore-keys: |
            testmon-cpu-main-${{ matrix.os }}-${{ matrix.version_python }}
            testmon-cpu-main-${{ matrix.os }}

      - name: Test with pytest
        if: matrix.version_python == '3.12'
        shell: bash
        run: |
          pixi run -e ${{ matrix.environment }} pytest

      - name: Upload coverage to Codecov
        if: runner.os == 'Linux' && matrix.version_python == '3.12'
        uses: codecov/codecov-action@v5

      - name: Upload test results to Codecov
        if: (!cancelled()) && runner.os == 'Linux' && matrix.version_python == '3.12'
        uses: codecov/test-results-action@v1